### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by brinrosenthal** [andreagobbi/pyBiRewire#2]
Hi, I was unable to load pyBiRewire due to the following error.  Any help much appreciated.  Thanks!

import BiRewire as br

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-195-808025dffc3a> in <module>()
      1 sys.path.append('/Users/brin/Google_Drive/UCSD/cluster_code/pyBiRewire-master/BiRewire/')
----> 2 import BiRewire as br

/Users/brin/Google_Drive/UCSD/cluster_code/pyBiRewire-master/BiRewire/__init__.py in <module>()
----> 1 from .wrapped import Rewiring,incidence,read_BRCA,similarity

ImportError: cannot import name Rewiring

**Comment by andreagobbi** [comment]
Fixed and pushed the new version (the error was in the igraph package renamed jgraph).
I suggest to use the Bioconductor release: https://bioconductor.org/packages/release/bioc/html/BiRewire.html because it is more update and tested. I have planned to rework a little this python version but right now I'm quite busy.
